SELECT * FROM ECOMM_DB.DBT_DEV.STG_ORDERS
SELECT * FROM ECOMM_DB.DBT_DEV.STG_ORDER_ITEMS

SHOW VIEWS IN SCHEMA ECOMM_DB.DBT_DEV;

SELECT "order_item_id", COUNT(*) FROM ECOMM_DB.RAW.OLIST_ORDER_ITEMS GROUP BY 1 ORDER BY 1;