SELECT * FROM ECOMM_DB.DBT_DEV.STG_ORDERS
SELECT * FROM ECOMM_DB.DBT_DEV.STG_ORDER_ITEMS
SELECT * FROM ECOMM_DB.DBT_DEV.STG_ORDER_REVIEWS


SHOW VIEWS IN SCHEMA ECOMM_DB.DBT_DEV;

SELECT "order_item_id", COUNT(*) FROM ECOMM_DB.RAW.OLIST_ORDER_ITEMS GROUP BY 1 ORDER BY 1;

SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT "review_id") AS unique_review_ids,
    COUNT(DISTINCT "order_id") AS unique_order_ids,
    COUNT(DISTINCT "review_id", "order_id") AS unique_combinations
FROM ECOMM_DB.RAW.OLIST_ORDER_REVIEWS;

SELECT *
FROM ECOMM_DB.RAW.OLIST_ORDER_REVIEWS
WHERE "review_id" IN (
    SELECT "review_id"
    FROM ECOMM_DB.RAW.OLIST_ORDER_REVIEWS
    GROUP BY 1
    HAVING COUNT(*) > 1
)
ORDER BY "review_id"