olist_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not_used'
      user: 'not_used'
      role: TRANSFORMER
      warehouse: COMPUTE_WH
      database: ECOMM_DB
      schema: DBT_DEV
      threads: 4