USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORMER;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE ECOMM_DB TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA ECOMM_DB.RAW TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA ECOMM_DB.DBT_DEV TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA ECOMM_DB.DBT_PROD TO ROLE TRANSFORMER;

GRANT SELECT ON ALL TABLES IN SCHEMA ECOMM_DB.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ECOMM_DB.RAW TO ROLE TRANSFORMER;

GRANT CREATE TABLE, CREATE VIEW ON SCHEMA ECOMM_DB.DBT_DEV TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA ECOMM_DB.DBT_PROD TO ROLE TRANSFORMER;

GRANT ROLE TRANSFORMER TO USER DEVJHO;
GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;

USE ROLE TRANSFORMER;
USE WAREHOUSE COMPUTE_WH;

-- Should succeed: reading raw data
SELECT COUNT(*) FROM ECOMM_DB.RAW.OLIST_ORDERS;

-- Should FAIL: writing to raw
CREATE TABLE ECOMM_DB.RAW.TEST_WRITE (id INT);

-- Should succeed: building in dbt's schema
CREATE VIEW ECOMM_DB.DBT_DEV.TEST_VIEW AS SELECT 1 AS id;
DROP VIEW ECOMM_DB.DBT_DEV.TEST_VIEW;